# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Step14' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Step14
  pod 'Firebase'
  pod 'Firebase/Auth'

  target 'Step14Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Step14UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
